<?php
/**
 * Created by PhpStorm.
 * User: hoo
 * Date: 2017/11/28
 * Time: 9:40
 */

namespace app\admin\model;

use app\admin\common\BaseModel;
use think\Model;

class UserModel extends BaseModel
{
    // 设置当前模型对应的完整数据表名称
    protected $table = 't_user';

    public function getResult()
    {
        return parent::getResultArray(); // TODO: Change the autogenerated stub
    }

    public function get_user_by_id($id)
    {
        return $this->where('id', '=', $id)->find();
    }

    /**
     * 获取单个用户
     * @param $params
     * @return array|false|\PDOStatement|string|Model
     */
    public function get_user($params = [])
    {
        $params['is_enable'] = isset($params['is_enable']) ?: true;
        $this->where($params);
        return $this;
    }

    /**
     * 获取多个用户
     * @param $params
     * @param $page
     * @param $limit
     * @return false|\PDOStatement|string|\think\Collection
     * @internal param $total
     */
    public function get_users($params = [])
    {
        $params['is_enable'] = isset($params['is_enable']) ?: true;
        $this->where($params);
        return $this->getResult();
    }
}